export type UserRole = 'admin' | 'doctor' | 'receptionist';

export interface UserRow {
  id: string; // UUID
  user_id: string;
  password: string;
  role: UserRole;
  created_at: string;
}

export interface PatientRow {
  id: string; // custom id per spec
  name: string;
  dob: string; // ISO date
  gender: 'Male' | 'Female' | 'Other';
  contact: string;
  address: string;
  age: number;
  created_at: string;
}

export interface DoctorRow {
  id: string; // custom id per spec
  name: string;
  contact: string;
  registration_number: string;
  opd_fees: number;
  created_at: string;
}

export interface ServiceRow {
  id: string; // UUID
  service_name: string;
  service_type: string;
  price: number;
  created_at: string;
}

export interface BillRow {
  id: string; // UUID
  patient_id: string;
  doctor_id: string;
  total_amount: number;
  discount: number;
  net_amount: number;
  status: 'paid' | 'pending' | 'partial';
  bill_number: string;
  mode_of_payment: 'Cash' | 'UPI' | 'Card';
  transaction_reference: string | null;
  created_at: string;
}

export interface BillItemRow {
  id: string; // UUID generated by Supabase
  bill_id: string; // UUID FK
  service_id: string; // UUID FK
  quantity: number;
  price: number;
  total: number;
}

export interface PrescriptionRow {
  id: string; // UUID
  patient_id: string;
  doctor_id: string;
  diagnosis: string;
  medicines: string;
  advice: string;
  created_at: string;
}

export interface AppointmentRow {
  id: string; // UUID
  patient_id: string;
  doctor_id: string;
  appointment_datetime: string; // ISO datetime
  status: 'booked' | 'completed' | 'cancelled';
  notes: string | null;
  created_at: string;
}

export interface SessionUser {
  userId: string;
  role: UserRole;
}