export type UserRole = 'admin' | 'doctor' | 'receptionist' | 'store_manager';

export interface UserRow {
  id: string; // UUID
  user_id: string;
  password: string;
  role: UserRole;
  created_at: string;
}

export interface PatientRow {
  id: string; // custom id per spec
  name: string;
  dob: string; // ISO date
  gender: 'Male' | 'Female' | 'Other';
  contact: string;
  address: string;
  age: number;
  created_at: string;
}

export interface DoctorRow {
  id: string; // custom id per spec
  name: string;
  contact: string;
  registration_number: string;
  opd_fees: number;
  created_at: string;
}

export interface ServiceRow {
  id: string; // UUID
  service_name: string;
  service_type: string;
  price: number;
  created_at: string;
}

export interface BillRow {
  id: string; // UUID
  patient_id: string | null;
  doctor_id: string | null; // Optional for medicine store bills
  total_amount: number;
  discount: number;
  net_amount: number;
  status: 'paid' | 'pending' | 'partial';
  bill_number: string;
  mode_of_payment: 'Cash' | 'UPI' | 'Card';
  transaction_reference: string | null;
  // Support for non-registered/guest patients
  guest_name?: string | null;
  guest_contact?: string | null;
  // Bill classification
  bill_type: 'services' | 'pharmacy' | 'mixed';
  // Medicine store specific fields
  prescription_id?: string | null;
  is_medicine_store_bill?: boolean;
  created_at: string;
}

export interface BillItemRow {
  id: string; // UUID generated by Supabase
  bill_id: string; // UUID FK
  // Either a service or an inventory/medicine item
  service_id?: string; // UUID FK
  inventory_item_id?: string; // UUID FK
  item_name?: string; // denormalized for print resilience
  quantity: number;
  price: number;
  total: number;
}

export interface PrescriptionRow {
  id: string; // UUID
  patient_id: string;
  doctor_id: string;
  diagnosis: string;
  medicines: string;
  advice: string;
  created_at: string;
}

export interface AppointmentRow {
  id: string; // UUID
  patient_id: string | null;
  doctor_id: string;
  appointment_datetime: string; // ISO datetime
  status: 'booked' | 'completed' | 'cancelled';
  notes: string | null;
  guest_name: string | null;
  guest_contact: string | null;
  created_at: string;
}

export interface SessionUser {
  userId: string;
  role: UserRole;
}

// Inventory & Stock Management Types

export interface InventoryItemRow {
  id: string; // UUID
  name: string;
  sku: string;
  unit: string; // e.g., tablet, bottle, unit
  cost_price: number;
  sale_price: number;
  opening_stock: number;
  current_stock: number;
  low_stock_threshold: number | null;
  // Medicine store specific fields
  category: string; // e.g., 'Tablets', 'Syrups', 'Injections', 'Devices'
  manufacturer: string;
  expiry_date: string | null;
  batch_number: string | null;
  hsn_code: string | null; // GST HSN code
  gst_rate: number; // GST percentage
  created_at: string;
}

export interface StockLedgerRow {
  id: string; // UUID
  item_id: string; // InventoryItemRow.id
  change: number; // positive for addition, negative for deduction
  reason: 'opening' | 'purchase' | 'adjustment' | 'dispense' | 'return' | 'correction';
  notes: string | null;
  reference_bill_id: string | null; // link to BillRow if dispense
  created_by: string | null; // user_id
  created_at: string;
}

// New types for medicine store
export interface MedicineStoreBillRow {
  id: string; // UUID
  bill_number: string;
  patient_id: string | null;
  guest_name: string | null;
  guest_contact: string | null;
  prescription_id: string | null;
  doctor_id: string | null;
  total_amount: number;
  discount: number;
  net_amount: number;
  gst_amount: number;
  status: 'paid' | 'pending' | 'partial';
  mode_of_payment: 'Cash' | 'UPI' | 'Card';
  transaction_reference: string | null;
  created_by: string; // user_id
  created_at: string;
}

export interface MedicineStoreBillItemRow {
  id: string; // UUID
  bill_id: string;
  inventory_item_id: string;
  item_name: string;
  quantity: number;
  price: number;
  gst_rate: number;
  gst_amount: number;
  total: number;
  created_at: string;
}

export interface StockPurchaseRow {
  id: string; // UUID
  supplier_name: string;
  supplier_contact: string;
  invoice_number: string;
  invoice_date: string;
  total_amount: number;
  gst_amount: number;
  net_amount: number;
  payment_status: 'paid' | 'pending' | 'partial';
  notes: string | null;
  created_by: string;
  created_at: string;
}

export interface StockPurchaseItemRow {
  id: string; // UUID
  purchase_id: string;
  inventory_item_id: string;
  item_name: string;
  quantity: number;
  cost_price: number;
  expiry_date: string | null;
  batch_number: string | null;
  total: number;
  created_at: string;
}