import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { getPathologyReportById, getPathologyTestOrderById, listPathologyTestResults } from '../api';
import { PathologyReportRow, PathologyTestOrderRow, PathologyTestResultRow } from '../types';
import { format } from 'date-fns';
import { CLINIC_ADDRESS_LINE_1, CLINIC_CONTACT, CLINIC_EMAIL, CLINIC_NAME, CLINIC_REG_NO, DOCTOR_NAME, DOCTOR_QUALIFICATION, DOCTOR_REG_NUMBER, DOCTOR_INFO_LINE, CLINIC_CONTACT_EMAIL_LINE, CLINIC_ADDRESS_FORMATTED } from '../config/clinic';

const PrintPathologyReport: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const [report, setReport] = useState<PathologyReportRow | null>(null);
  const [order, setOrder] = useState<PathologyTestOrderRow | null>(null);
  const [results, setResults] = useState<PathologyTestResultRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchData = async () => {
      if (!id) return;
      
      try {
        setLoading(true);
        const reportData = await getPathologyReportById(id);
        if (!reportData) {
          setError('Report not found');
          setLoading(false);
          return;
        }
        
        setReport(reportData);
        
        const orderData = await getPathologyTestOrderById(reportData.order_id);
        if (orderData) {
          setOrder(orderData);
        }
        
        const resultsData = await listPathologyTestResults(reportData.order_id);
        setResults(resultsData);
      } catch (err: any) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [id]);

  if (loading) {
    return (
      <div className="flex justify-center items-center h-screen">
        <div className="text-lg">Loading report...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex justify-center items-center h-screen">
        <div className="text-red-500 text-lg">Error: {error}</div>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="flex justify-center items-center h-screen">
        <div className="text-lg">Report not found</div>
      </div>
    );
  }

  // Extract patient and doctor information if available
  const patientId = report.patient_id;
  const doctorId = report.doctor_id;

  return (
    <div className="p-8 max-w-4xl mx-auto bg-white">
      <div className="mb-6">
        <table className="w-full border-b border-gray-800 mb-2">
          <tbody>
            <tr>
              <td className="text-left align-top w-1/2 pb-2">
                <h1 className="text-2xl font-bold">{DOCTOR_NAME}</h1>
                <div className="text-sm">{DOCTOR_INFO_LINE}</div>
                <div className="text-sm mt-1">{CLINIC_NAME}</div>
                <div className="text-sm">Pathology Laboratory Services</div>
              </td>
              <td className="border-l border-gray-800 text-left align-top w-1/2 pl-2 pb-2">
                <div className="text-sm">{CLINIC_ADDRESS_FORMATTED}</div>
                <div className="text-sm">Email: {CLINIC_EMAIL}</div>
                <div className="text-sm">{CLINIC_CONTACT}</div>
              </td>
            </tr>
          </tbody>
        </table>
        <p className="text-sm text-gray-500 mt-2 text-center">Report Generated: {format(new Date(report.report_date), 'dd/MM/yyyy HH:mm:ss')}</p>
      </div>

      <div className="mb-6 grid grid-cols-2 gap-4">
        <div>
          <h2 className="text-lg font-semibold border-b pb-1">Patient Information</h2>
          <p><span className="font-medium">Patient ID:</span> {patientId}</p>
          <p><span className="font-medium">Report ID:</span> {report.id}</p>
        </div>
        <div>
          <h2 className="text-lg font-semibold border-b pb-1">Order Information</h2>
          <p><span className="font-medium">Order ID:</span> {report.order_id}</p>
          <p><span className="font-medium">Generated By:</span> {report.generated_by}</p>
        </div>
      </div>

      <div className="mb-6">
        <h2 className="text-lg font-semibold border-b pb-1">Test Results</h2>
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Test Name</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Result</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Units</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Reference Range</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {results.map((result) => (
                <tr key={result.id}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                    {result.test_id} {/* In a real implementation, this would show the test name */}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{result.result_value}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{result.units}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{result.reference_range}</td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${
                      result.status === 'completed' ? 'bg-green-100 text-green-800' :
                      result.status === 'pending' ? 'bg-yellow-100 text-yellow-800' :
                      'bg-blue-100 text-blue-800'
                    }`}>
                      {result.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div className="mb-6">
        <h2 className="text-lg font-semibold border-b pb-1">Report Notes</h2>
        <p>{report.notes || 'No additional notes'}</p>
      </div>

      <div className="border-t pt-4 text-center text-sm text-gray-500">
        <p>This is a computer-generated report and is valid without signature.</p>
        <p>For any queries regarding this report, please contact the lab.</p>
      </div>

      <div className="fixed bottom-4 right-4">
        <button 
          onClick={() => window.print()}
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
        >
          Print Report
        </button>
      </div>
    </div>
  );
};

export default PrintPathologyReport;