export type UserRole = 'admin' | 'doctor' | 'receptionist' | 'store_manager';

export interface UserRow {
  id: string; // UUID
  user_id: string;
  password: string;
  role: UserRole;
  created_at: string;
}

export interface PatientRow {
  id: string; // UUID primary key (auto-generated)
  patient_id: string; // custom patient id per spec (YYYY/XXXX)
  name: string;
  age: number;
  gender: 'Male' | 'Female' | 'Other';
  contact: string;
  address: string;
  created_at: string;
}

export interface DoctorRow {
  id: string; // UUID primary key (auto-generated)
  doctor_id: string; // custom doctor id per spec (DOC-YYYY-XXXX-XXX)
  name: string;
  contact: string;
  registration_number: string;
  opd_fees: number;
  created_at: string;
}

export interface DoctorAvailabilityRow {
  id: string;
  doctor_id: string;
  day_of_week: number | null; // 0 = Sunday, 6 = Saturday, null for specific dates
  specific_date: string | null; // YYYY-MM-DD format, null for recurring availability
  start_time: string; // HH:MM format
  end_time: string; // HH:MM format
  is_available: boolean;
  created_at: string;
  updated_at: string;
}

export interface ServiceRow {
  id: string; // UUID
  service_name: string;
  service_type: string;
  price: number;
  created_at: string;
}

export interface BillRow {
  id: string; // UUID
  patient_id: string | null;
  doctor_id: string | null; // Optional for medicine store bills
  total_amount: number;
  discount: number;
  discount_percentage?: number;
  net_amount: number;
  status: 'paid' | 'pending' | 'partial';
  bill_number: string;
  mode_of_payment: 'Cash' | 'UPI' | 'Card';
  transaction_reference: string | null;
  referred_by?: string | null;
  // Support for non-registered/guest patients
  guest_name?: string | null;
  guest_contact?: string | null;
  // Bill classification
  bill_type: 'services' | 'pharmacy' | 'mixed';
  // Medicine store specific fields
  prescription_id?: string | null;
  is_medicine_store_bill?: boolean;
  created_at: string;
}

export interface BillItemRow {
  id: string; // UUID generated by Supabase
  bill_id: string; // UUID FK
  // Either a service or an inventory/medicine item
  service_id?: string; // UUID FK
  inventory_item_id?: string; // UUID FK
  item_name?: string; // denormalized for print resilience
  quantity: number;
  price: number;
  total: number;
  batch_number?: string | null;
  expiry_date?: string | null;
}

export interface PrescriptionRow {
  id: string; // UUID
  patient_id: string;
  doctor_id: string;
  diagnosis: string;
  medicines: string;
  advice: string;
  serial_number: string;
  created_at: string;
}

export interface AppointmentRow {
  id: string; // UUID
  patient_id: string | null;
  doctor_id: string;
  appointment_date: string; // Required date field in database
  appointment_datetime?: string; // ISO datetime - optional, may not exist in DB
  status: 'booked' | 'completed' | 'cancelled';
  notes?: string | null; // Optional - may not exist in DB
  guest_name?: string | null; // Optional - may not exist in DB
  guest_contact?: string | null; // Optional - may not exist in DB
  created_at: string;
}

export interface SessionUser {
  userId: string;
  role: UserRole;
}

// Inventory & Stock Management Types

export interface InventoryItemRow {
  id: string; // UUID
  name: string;
  sku: string;
  unit: string; // e.g., tablet, bottle, unit
  cost_price: number;
  sale_price: number;
  opening_stock: number;
  current_stock: number;
  low_stock_threshold: number | null;
  // Medicine store specific fields
  category: string; // e.g., 'Tablets', 'Syrups', 'Injections', 'Devices'
  manufacturer: string;
  expiry_date: string | null;
  batch_number: string | null;
  hsn_code: string | null; // GST HSN code
  gst_rate: number; // GST percentage
  created_at: string;
}

export interface StockLedgerRow {
  id: string; // UUID
  item_id: string; // InventoryItemRow.id
  change: number; // positive for addition, negative for deduction
  reason: 'opening' | 'purchase' | 'adjustment' | 'dispense' | 'return' | 'correction';
  notes: string | null;
  reference_bill_id: string | null; // link to BillRow if dispense
  created_by: string | null; // user_id
  created_at: string;
}

// New types for medicine store
export interface MedicineStoreBillRow {
  id: string; // UUID
  bill_number: string;
  patient_id: string | null;
  guest_name: string | null;
  guest_contact: string | null;
  prescription_id: string | null;
  doctor_id: string | null;
  total_amount: number;
  discount: number;
  net_amount: number;
  gst_amount: number;
  status: 'paid' | 'pending' | 'partial';
  mode_of_payment: 'Cash' | 'UPI' | 'Card';
  transaction_reference: string | null;
  created_by: string; // user_id
  created_at: string;
}

export interface MedicineStoreBillItemRow {
  id: string; // UUID
  bill_id: string;
  inventory_item_id: string;
  item_name: string;
  quantity: number;
  price: number;
  gst_rate: number;
  gst_amount: number;
  total: number;
  created_at: string;
}

export interface StockPurchaseRow {
  id: string; // UUID
  supplier_name: string;
  supplier_contact: string;
  invoice_number: string;
  invoice_date: string;
  total_amount: number;
  gst_amount: number;
  net_amount: number;
  payment_status: 'paid' | 'pending' | 'partial';
  notes: string | null;
  created_by: string;
  created_at: string;
}

export interface StockPurchaseItemRow {
  id: string; // UUID
  purchase_id: string;
  inventory_item_id: string;
  item_name: string;
  quantity: number;
  cost_price: number;
  sale_price: number;
  expiry_date: string | null;
  batch_number: string | null;
  hsn_code: string | null;
  gst_rate: number;
  total_amount: number;
  created_at: string;
}

// Pathology Lab Types
export interface PathologyTestRow {
  id: string; // UUID
  test_name: string;
  test_code: string;
  category: string; // e.g., 'Hematology', 'Biochemistry', 'Microbiology', 'Immunology'
  description: string;
  price: number;
  sample_type: string; // e.g., 'Blood', 'Urine', 'Stool', 'Saliva'
  report_format: string; // Custom report format if needed
  reference_ranges?: string; // JSON string containing reference ranges
  method?: string; // Testing method
  units?: string; // Measurement units
  created_at: string;
}

export interface PathologyTestOrderRow {
  id: string; // UUID
  patient_id: string;
  test_ids: string[]; // Array of test IDs ordered
  doctor_id?: string; // Ordering doctor
  technician_id?: string; // Assigned technician
  order_date: string; // ISO date
  sample_collection_date?: string; // ISO date
  sample_collector?: string; // Name of collector
  report_generation_date?: string; // ISO date
  report_status: 'ordered' | 'sample_collected' | 'in_progress' | 'completed' | 'verified' | 'delivered';
  priority: 'normal' | 'urgent' | 'stat';
  notes?: string;
  created_at: string;
}

export interface PathologyTestResultRow {
  id: string; // UUID
  order_id: string; // Link to the order
  test_id: string; // Link to the test
  result_value: string; // The actual result value
  units?: string; // Units for the result
  reference_range?: string; // Normal range for comparison
  status: 'pending' | 'in_progress' | 'completed' | 'verified';
  result_date: string; // When the result was entered
  technician_id?: string; // Who entered the result
  pathologist_id?: string; // Who verified the result
  notes?: string;
  created_at: string;
}

export interface PathologyReportRow {
  id: string; // UUID
  order_id: string; // Link to the order
  patient_id: string; // Patient info
  doctor_id?: string; // Ordering doctor
  report_date: string; // Date of report generation
  report_status: 'draft' | 'generated' | 'verified' | 'delivered';
  report_data: string; // JSON string containing the full report data
  generated_by: string; // User who generated the report
  verified_by?: string; // User who verified the report
  delivery_status: 'pending' | 'delivered' | 'collected';
  delivery_date?: string; // Date of delivery
  notes?: string;
  created_at: string;
}